service: serverless-demo
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variable

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
